<?php

/**
* My Application bootstrap file.
*/
use Nette\Diagnostics\Debugger,
    Nette\Utils\Strings,
    Nette\Application\Routers\Route,
    Nette\Application\Routers\CliRouter,
    Nette\Application\Routers\SimpleRouter,
    Nette\Http\Url,
    Nette\Http\UrlScript,
    Nette\Http;


// Load Nette Framework or autoloader generated by Composer
require LIBS_DIR . '/autoload.php';


// Configure application
$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode($configurator::AUTO);
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
->addDirectory(APP_DIR)
->addDirectory(LIBS_DIR)
->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$container = $configurator->createContainer();

if ($container->params['consoleMode']) {
    $container->removeService('httpRequest');
    $container->addService('httpRequest', function() {
        // Podle potreby muzeme pouzit nastaveni z configu nebo vzit z parametru prikazove radky, aj.
        $uri = new UrlScript;
        $uri->scheme = 'http';
        $uri->port = Url::$defaultPorts['http'];
        $uri->host = 'example.com';
        $uri->path = '/';
        $uri->canonicalize();
        $uri->path = Strings::fixEncoding($uri->path);
        $uri->scriptPath = '/';
        return new Http\Request($uri, array(), array(), array(), array(), array(), 'GET', null, null);
    });
}

// Setup router
if ($container->params['consoleMode']) {
    $container->application->allowedMethods = FALSE;
    $container->router[] = new CliRouter(array("action"=>'Homepage:default'));
} else {
    $container->router[] = new Route('index.php', 'Homepage:default', Route::ONE_WAY);
    $container->router[] = new Route('<presenter>/<action>[/<id>]', 'Homepage:default');
}

// Configure and run the application!
$container->application->run();
